version: "3.9"
services:
  segmenting-server:
    build: segmenting-server/
    network_mode: "service:frontend"
    volumes:
      - ./segmenting-server/:/app
  ocr-server:
    build: ocr-server/
    network_mode: "service:frontend"
    volumes:
      - ./ocr-server/:/app
  api:
    build: api/
    network_mode: "service:frontend"
    volumes:
      - ./api/:/app
      - ./api/data:/app/data
  frontend:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./src/:/app/src
